In [1]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import AlignIO
from Bio import SeqIO
import pprint
import pandas as pd

In [2]:
###after gfftobed and bedtools merge
path = "/mnt/pbil/"

### Gnetum

In [18]:
#gfftobed -m G.montanum.final.gff > G.montanum.final.mRNA.bed
#bedtools merge -i G.montanum.final.mRNA.bed -delim "," -c 4,6 -o collapse > G.montanum.final.mRNA.merge.bed


prot_file =path+"Infer_Anth/data/gymnosperms/complete_genomes/gnetum/G.montanum.final.pep"
bed_file = path+"Infer_Anth/data/gymnosperms/complete_genomes/gnetum/G.montanum.final.mRNA.bed"

In [21]:
BED = pd.read_csv(bed_file, sep="\t", header=None, names=["chr", "start", "end", "id", "unk", "strand"])

In [22]:
BED.head()

     chr    start      end                   id unk strand
0  Hic_9   691704   693551  ID=TnS000552037t01;   .      -
1  Hic_9   693649   694114  ID=TnS000552037t02;   .      -
2  Hic_9   694527   694992  ID=TnS000552037t03;   .      -
3  Hic_9   810502   810682  ID=TnS000339411t01;   .      -
4  Hic_9  1224191  1230325  ID=TnS000339411t02;   .      +

In [10]:
#TnS000447071t02 gene=TnS000447071g02 [translate_table: standard]

#grep ">" gmon.all.pep.fasta | wc -l ---> 27354


records = SeqIO.parse(prot_file, "fasta")
sequences = []
for rec in records:
    seq = SeqRecord(rec.seq, id=rec.name ,name="",description="")
    sequences.append(seq)

In [12]:
with open(path+"Infer_Anth/data/gymnosperms/complete_genomes/gnetum/gmon.all.pep.fasta", "w") as output_handle:
    SeqIO.write(sequences, output_handle, "fasta")

In [13]:
fasta_names = [seq.id for seq in sequences]

In [23]:

BED["names"]= BED.id.apply(lambda x: x.split(";")[0].split("=")[1])
BED.head()

     chr    start      end                   id unk strand            names
0  Hic_9   691704   693551  ID=TnS000552037t01;   .      -  TnS000552037t01
1  Hic_9   693649   694114  ID=TnS000552037t02;   .      -  TnS000552037t02
2  Hic_9   694527   694992  ID=TnS000552037t03;   .      -  TnS000552037t03
3  Hic_9   810502   810682  ID=TnS000339411t01;   .      -  TnS000339411t01
4  Hic_9  1224191  1230325  ID=TnS000339411t02;   .      +  TnS000339411t02

In [26]:
BED_nosplicing = pd.DataFrame(BED[BED.names.isin(fasta_names)])
BED_nosplicing["seqnames"] = ["Chr"+i.split("_")[1] for i in BED_nosplicing.chr]
BED_nosplicing["ranges"] = [str(i)+"-"+str(j) for i,j in zip(BED_nosplicing["start"], BED_nosplicing["end"])]
BED_nosplicing["type"] = ["gene"]*len(BED_nosplicing)
BED_nosplicing["gene_id"] = BED_nosplicing["names"]
BED_nosplicing["phase"] = BED_nosplicing["strand"]
BED_nosplicing["source"] = ["dryad.ht76hdrdr "]*len(BED_nosplicing)
BED_nosplicing.head()

,chr,start,end,id,unk,strand,names,seqnames,ranges,type,gene_id,phase,source
0,Hic_9,691704,693551,ID=TnS000552037t01;,.,-,TnS000552037t01,Chr9,691704-693551,gene,TnS000552037t01,-,dryad.ht76hdrdr
1,Hic_9,693649,694114,ID=TnS000552037t02;,.,-,TnS000552037t02,Chr9,693649-694114,gene,TnS000552037t02,-,dryad.ht76hdrdr
2,Hic_9,694527,694992,ID=TnS000552037t03;,.,-,TnS000552037t03,Chr9,694527-694992,gene,TnS000552037t03,-,dryad.ht76hdrdr
3,Hic_9,810502,810682,ID=TnS000339411t01;,.,-,TnS000339411t01,Chr9,810502-810682,gene,TnS000339411t01,-,dryad.ht76hdrdr
4,Hic_9,1224191,1230325,ID=TnS000339411t02;,.,+,TnS000339411t02,Chr9,1224191-1230325,gene,TnS000339411t02,+,dryad.ht76hdrdr

In [27]:
subset = pd.DataFrame(BED_nosplicing[["seqnames", "strand", "source", "type", "phase", "names", "gene_id", "start", "end"]])
subset.sort_values(by=["seqnames", "start"], inplace=True)
subset.to_csv(path+"Infer_Anth/data/gymnosperms/complete_genomes/gnetum/gnetum_montanum_nosplicing.tsv", sep="\t", index=None)

### ginkgo

In [31]:
#gfftobed -m Ginkgo_biloba.all.v2.gff3 > Ginkgo_biloba.mRNA.bed


prot_file =path+"Infer_Anth/data/gymnosperms/complete_genomes/ginkgo/Ginkgo_biloba.pep.all.v2.fa"
bed_file = path+"Infer_Anth/data/gymnosperms/complete_genomes/ginkgo/Ginkgo_biloba.mRNA.sort.bed"

In [32]:
BED = pd.read_csv(bed_file, sep="\t", header=None, names=["chr", "start", "end", "id", "unk", "strand"])
BED.head()

    chr    start      end                                        id unk strand
0  chr1  3479004  3483204  ID=evm.model.chr1.1;Parent=evm.TU.chr1.1   .      -
1  chr1  4289655  4323087  ID=evm.model.chr1.2;Parent=evm.TU.chr1.2   .      +
2  chr1  4818617  4998879  ID=evm.model.chr1.3;Parent=evm.TU.chr1.3   .      -
3  chr1  5235305  5237785  ID=evm.model.chr1.4;Parent=evm.TU.chr1.4   .      +
4  chr1  5432830  5434000  ID=evm.model.chr1.5;Parent=evm.TU.chr1.5   .      -

In [33]:
#evm.model.chr1.1

records = SeqIO.parse(prot_file, "fasta")
sequences = []
for rec in records:
    seq = SeqRecord(rec.seq, id=rec.name.replace(".", "_") ,name="",description="")
    sequences.append(seq)


fasta_names = [seq.id for seq in sequences]

In [34]:
seq

SeqRecord(seq=Seq('LLFQLFIPILAKEERNGEARFWATDEAHSIESMGSELLSNMQRFASQVSNARQL...IDH'), id='evm_model_chr10_2136', name='', description='', dbxrefs=[])

In [35]:
with open(path+"Infer_Anth/data/gymnosperms/complete_genomes/ginkgo/Ginkgo_biloba.pep.fa", "w") as output_handle:
    SeqIO.write(sequences, output_handle, "fasta")

In [37]:

BED["names"]= BED.id.apply(lambda x: x.split(";")[0].split("=")[1].replace(".","_"))
BED.head()

,chr,start,end,id,unk,strand,names
0,chr1,3479004,3483204,ID=evm.model.chr1.1;Parent=evm.TU.chr1.1,.,-,evm_model_chr1_1
1,chr1,4289655,4323087,ID=evm.model.chr1.2;Parent=evm.TU.chr1.2,.,+,evm_model_chr1_2
2,chr1,4818617,4998879,ID=evm.model.chr1.3;Parent=evm.TU.chr1.3,.,-,evm_model_chr1_3
3,chr1,5235305,5237785,ID=evm.model.chr1.4;Parent=evm.TU.chr1.4,.,+,evm_model_chr1_4
4,chr1,5432830,5434000,ID=evm.model.chr1.5;Parent=evm.TU.chr1.5,.,-,evm_model_chr1_5

In [38]:
BED_nosplicing = pd.DataFrame(BED[BED.names.isin(fasta_names)])
BED_nosplicing["seqnames"] = BED_nosplicing.chr
BED_nosplicing["ranges"] = [str(i)+"-"+str(j) for i,j in zip(BED_nosplicing["start"], BED_nosplicing["end"])]
BED_nosplicing["type"] = ["gene"]*len(BED_nosplicing)
BED_nosplicing["gene_id"] = BED_nosplicing["names"]
BED_nosplicing["phase"] = BED_nosplicing["strand"]
BED_nosplicing["source"] = ["ginkgoDB"]*len(BED_nosplicing)
BED_nosplicing.head()

,chr,start,end,id,unk,strand,names,seqnames,ranges,type,gene_id,phase,source
0,chr1,3479004,3483204,ID=evm.model.chr1.1;Parent=evm.TU.chr1.1,.,-,evm_model_chr1_1,chr1,3479004-3483204,gene,evm_model_chr1_1,-,ginkgoDB
1,chr1,4289655,4323087,ID=evm.model.chr1.2;Parent=evm.TU.chr1.2,.,+,evm_model_chr1_2,chr1,4289655-4323087,gene,evm_model_chr1_2,+,ginkgoDB
2,chr1,4818617,4998879,ID=evm.model.chr1.3;Parent=evm.TU.chr1.3,.,-,evm_model_chr1_3,chr1,4818617-4998879,gene,evm_model_chr1_3,-,ginkgoDB
3,chr1,5235305,5237785,ID=evm.model.chr1.4;Parent=evm.TU.chr1.4,.,+,evm_model_chr1_4,chr1,5235305-5237785,gene,evm_model_chr1_4,+,ginkgoDB
4,chr1,5432830,5434000,ID=evm.model.chr1.5;Parent=evm.TU.chr1.5,.,-,evm_model_chr1_5,chr1,5432830-5434000,gene,evm_model_chr1_5,-,ginkgoDB

In [39]:
subset = pd.DataFrame(BED_nosplicing[["seqnames", "strand", "source", "type", "phase", "names", "gene_id", "start", "end"]])
subset.sort_values(by=["seqnames", "start"], inplace=True)
subset.to_csv(path+"Infer_Anth/data/gymnosperms/complete_genomes/ginkgo/Ginkgo_biloba.nosplicing.tsv", sep="\t", index=None)

### cycas

In [40]:
prot_file =path+"Infer_Anth/data/gymnosperms/complete_genomes/cycas/Cycas_panzhihuaensis_genome.pep"
bed_file = path+"Infer_Anth/data/gymnosperms/complete_genomes/cycas/Cycas_panzhihuaensis.mRNA.sort.bed"

In [41]:
BED = pd.read_csv(bed_file, sep="\t", header=None, names=["chr", "start", "end", "id", "unk", "strand"])
BED.head()

    chr  start    end                id unk strand
0  chr1  12729  14425  ID=CYCAS_000001;   .      +
1  chr1  15423  16870  ID=CYCAS_000002;   .      -
2  chr1  49743  50292  ID=CYCAS_000003;   .      -
3  chr1  50790  51273  ID=CYCAS_000004;   .      +
4  chr1  70653  73286  ID=CYCAS_000005;   .      -

In [42]:
records = SeqIO.parse(prot_file, "fasta")
sequences = []
for rec in records:
    seq = SeqRecord(rec.seq, id=rec.name ,name="",description="")
    sequences.append(seq)


fasta_names = [seq.id for seq in sequences]

In [45]:
with open(path+"Infer_Anth/data/gymnosperms/complete_genomes/cycas/cycas.pep.fa", "w") as output_handle:
    SeqIO.write(sequences, output_handle, "fasta")

In [43]:
BED["names"]= BED.id.apply(lambda x: x.split(";")[0].split("=")[1])
BED.head()

    chr  start    end                id unk strand         names
0  chr1  12729  14425  ID=CYCAS_000001;   .      +  CYCAS_000001
1  chr1  15423  16870  ID=CYCAS_000002;   .      -  CYCAS_000002
2  chr1  49743  50292  ID=CYCAS_000003;   .      -  CYCAS_000003
3  chr1  50790  51273  ID=CYCAS_000004;   .      +  CYCAS_000004
4  chr1  70653  73286  ID=CYCAS_000005;   .      -  CYCAS_000005

In [44]:
BED_nosplicing = pd.DataFrame(BED[BED.names.isin(fasta_names)])
BED_nosplicing["seqnames"] = BED_nosplicing.chr
BED_nosplicing["ranges"] = [str(i)+"-"+str(j) for i,j in zip(BED_nosplicing["start"], BED_nosplicing["end"])]
BED_nosplicing["type"] = ["gene"]*len(BED_nosplicing)
BED_nosplicing["gene_id"] = BED_nosplicing["names"]
BED_nosplicing["phase"] = BED_nosplicing["strand"]
BED_nosplicing["source"] = ["ginkgoDB"]*len(BED_nosplicing)
BED_nosplicing.head()

,chr,start,end,id,unk,strand,names,seqnames,ranges,type,gene_id,phase,source
0,chr1,12729,14425,ID=CYCAS_000001;,.,+,CYCAS_000001,chr1,12729-14425,gene,CYCAS_000001,+,ginkgoDB
1,chr1,15423,16870,ID=CYCAS_000002;,.,-,CYCAS_000002,chr1,15423-16870,gene,CYCAS_000002,-,ginkgoDB
2,chr1,49743,50292,ID=CYCAS_000003;,.,-,CYCAS_000003,chr1,49743-50292,gene,CYCAS_000003,-,ginkgoDB
3,chr1,50790,51273,ID=CYCAS_000004;,.,+,CYCAS_000004,chr1,50790-51273,gene,CYCAS_000004,+,ginkgoDB
4,chr1,70653,73286,ID=CYCAS_000005;,.,-,CYCAS_000005,chr1,70653-73286,gene,CYCAS_000005,-,ginkgoDB

In [46]:
subset = pd.DataFrame(BED_nosplicing[["seqnames", "strand", "source", "type", "phase", "names", "gene_id", "start", "end"]])
subset.sort_values(by=["seqnames", "start"], inplace=True)
subset.to_csv(path+"Infer_Anth/data/gymnosperms/complete_genomes/cycas/cycas.nosplicing.tsv", sep="\t", index=None)

### Torreya

In [28]:
prot_file =path+"Infer_Anth/data/gymnosperms/complete_genomes/torreya/Tgrandis_chr.protein.fa"
bed_file = path+"Infer_Anth/data/gymnosperms/complete_genomes/torreya/Tgrandis_chr.mRNA.sorted.bed"

In [29]:
BED = pd.read_csv(bed_file, sep="\t", header=None, names=["chr", "start", "end", "id", "unk", "strand"])
BED.head()

,chr,start,end,id,unk,strand
0,Chr0,101673,104001,ID=TG0g00001-mRNA1;Name=TG0g00001-mRNA1;Parent...,.,+
1,Chr0,3457019,3457759,ID=TG0g00002-mRNA1;Name=TG0g00002-mRNA1;Parent...,.,+
2,Chr0,3772709,3773944,ID=TG0g00003-mRNA1;Name=TG0g00003-mRNA1;Parent...,.,+
3,Chr0,3892715,3894468,ID=TG0g00004-mRNA1;Name=TG0g00004-mRNA1;Parent...,.,+
4,Chr0,4264593,4339837,ID=TG0g00005-mRNA1;Name=TG0g00005-mRNA1;Parent...,.,-

In [30]:
records = SeqIO.parse(prot_file, "fasta")
sequences = []
for rec in records:
    seq = SeqRecord(rec.seq, id=rec.name ,name="",description="")
    sequences.append(seq)


fasta_names = [seq.id for seq in sequences]

In [6]:
with open(path+"Infer_Anth/data/gymnosperms/complete_genomes/torreya/torreya.pep.fa", "w") as output_handle:
    SeqIO.write(sequences, output_handle, "fasta")

In [31]:
BED["names"]= BED.id.apply(lambda x: x.split(";")[0].split("=")[1])
BED.head()

,chr,start,end,id,unk,strand,names
0,Chr0,101673,104001,ID=TG0g00001-mRNA1;Name=TG0g00001-mRNA1;Parent...,.,+,TG0g00001-mRNA1
1,Chr0,3457019,3457759,ID=TG0g00002-mRNA1;Name=TG0g00002-mRNA1;Parent...,.,+,TG0g00002-mRNA1
2,Chr0,3772709,3773944,ID=TG0g00003-mRNA1;Name=TG0g00003-mRNA1;Parent...,.,+,TG0g00003-mRNA1
3,Chr0,3892715,3894468,ID=TG0g00004-mRNA1;Name=TG0g00004-mRNA1;Parent...,.,+,TG0g00004-mRNA1
4,Chr0,4264593,4339837,ID=TG0g00005-mRNA1;Name=TG0g00005-mRNA1;Parent...,.,-,TG0g00005-mRNA1

In [32]:
BED_nosplicing = pd.DataFrame(BED[BED.names.isin(fasta_names)])
BED_nosplicing["seqnames"] = BED_nosplicing.chr
BED_nosplicing["ranges"] = [str(i)+"-"+str(j) for i,j in zip(BED_nosplicing["start"], BED_nosplicing["end"])]
BED_nosplicing["type"] = ["gene"]*len(BED_nosplicing)
BED_nosplicing["gene_id"] = BED_nosplicing["names"]
BED_nosplicing["phase"] = BED_nosplicing["strand"]
BED_nosplicing["source"] = ["figshare_tgrandis"]*len(BED_nosplicing)
BED_nosplicing.head()

,chr,start,end,id,unk,strand,names,seqnames,ranges,type,gene_id,phase,source
0,Chr0,101673,104001,ID=TG0g00001-mRNA1;Name=TG0g00001-mRNA1;Parent...,.,+,TG0g00001-mRNA1,Chr0,101673-104001,gene,TG0g00001-mRNA1,+,figshare_tgrandis
1,Chr0,3457019,3457759,ID=TG0g00002-mRNA1;Name=TG0g00002-mRNA1;Parent...,.,+,TG0g00002-mRNA1,Chr0,3457019-3457759,gene,TG0g00002-mRNA1,+,figshare_tgrandis
2,Chr0,3772709,3773944,ID=TG0g00003-mRNA1;Name=TG0g00003-mRNA1;Parent...,.,+,TG0g00003-mRNA1,Chr0,3772709-3773944,gene,TG0g00003-mRNA1,+,figshare_tgrandis
3,Chr0,3892715,3894468,ID=TG0g00004-mRNA1;Name=TG0g00004-mRNA1;Parent...,.,+,TG0g00004-mRNA1,Chr0,3892715-3894468,gene,TG0g00004-mRNA1,+,figshare_tgrandis
4,Chr0,4264593,4339837,ID=TG0g00005-mRNA1;Name=TG0g00005-mRNA1;Parent...,.,-,TG0g00005-mRNA1,Chr0,4264593-4339837,gene,TG0g00005-mRNA1,-,figshare_tgrandis

In [33]:
subset = pd.DataFrame(BED_nosplicing[["seqnames", "strand", "source", "type", "phase", "names", "gene_id", "start", "end"]])
subset.sort_values(by=["seqnames", "start"], inplace=True)
subset.to_csv(path+"Infer_Anth/data/gymnosperms/complete_genomes/torreya/torreya.nosplicing.tsv", sep="\t", index=None)

### welwitshcia

In [10]:
prot_file =path+"Infer_Anth/data/gymnosperms/complete_genomes/welwitschia/W.mirabilis.final.new.pep"
bed_file = path+"Infer_Anth/data/gymnosperms/complete_genomes/welwitschia/W.mirabilis.sorted.bed"

In [11]:
BED = pd.read_csv(bed_file, sep="\t", header=None, names=["chr", "start", "end", "id", "unk", "strand"])
BED.head()

     chr    start      end                     id unk strand
0  Chr01   121596   152397  ID=W.mirabilis.21820;   .      +
1  Chr01   332961   336195  ID=W.mirabilis.21821;   .      -
2  Chr01   973390  1086418  ID=W.mirabilis.21822;   .      -
3  Chr01  1326186  1330521  ID=W.mirabilis.21823;   .      +
4  Chr01  1672072  1771564  ID=W.mirabilis.21824;   .      +

In [12]:
records = SeqIO.parse(prot_file, "fasta")
sequences = []
for rec in records:
    seq = SeqRecord(rec.seq, id=rec.name.replace(".","_") ,name="",description="")
    sequences.append(seq)


fasta_names = [seq.id for seq in sequences]

In [14]:
with open(path+"Infer_Anth/data/gymnosperms/complete_genomes/welwitschia/welwitschia.pep.fa", "w") as output_handle:
    SeqIO.write(sequences, output_handle, "fasta")

In [15]:
BED["names"]= BED.id.apply(lambda x: x.split(";")[0].split("=")[1].replace(".","_")
                        )
BED.head()

,chr,start,end,id,unk,strand,names
0,Chr01,121596,152397,ID=W.mirabilis.21820;,.,+,W_mirabilis_21820
1,Chr01,332961,336195,ID=W.mirabilis.21821;,.,-,W_mirabilis_21821
2,Chr01,973390,1086418,ID=W.mirabilis.21822;,.,-,W_mirabilis_21822
3,Chr01,1326186,1330521,ID=W.mirabilis.21823;,.,+,W_mirabilis_21823
4,Chr01,1672072,1771564,ID=W.mirabilis.21824;,.,+,W_mirabilis_21824

In [16]:
BED_nosplicing = pd.DataFrame(BED[BED.names.isin(fasta_names)])
BED_nosplicing["seqnames"] = BED_nosplicing.chr
BED_nosplicing["ranges"] = [str(i)+"-"+str(j) for i,j in zip(BED_nosplicing["start"], BED_nosplicing["end"])]
BED_nosplicing["type"] = ["gene"]*len(BED_nosplicing)
BED_nosplicing["gene_id"] = BED_nosplicing["names"]
BED_nosplicing["phase"] = BED_nosplicing["strand"]
BED_nosplicing["source"] = ["dryad_ht76hdrdr"]*len(BED_nosplicing)
BED_nosplicing.head()

,chr,start,end,id,unk,strand,names,seqnames,ranges,type,gene_id,phase,source
0,Chr01,121596,152397,ID=W.mirabilis.21820;,.,+,W_mirabilis_21820,Chr01,121596-152397,gene,W_mirabilis_21820,+,dryad_ht76hdrdr
1,Chr01,332961,336195,ID=W.mirabilis.21821;,.,-,W_mirabilis_21821,Chr01,332961-336195,gene,W_mirabilis_21821,-,dryad_ht76hdrdr
2,Chr01,973390,1086418,ID=W.mirabilis.21822;,.,-,W_mirabilis_21822,Chr01,973390-1086418,gene,W_mirabilis_21822,-,dryad_ht76hdrdr
3,Chr01,1326186,1330521,ID=W.mirabilis.21823;,.,+,W_mirabilis_21823,Chr01,1326186-1330521,gene,W_mirabilis_21823,+,dryad_ht76hdrdr
4,Chr01,1672072,1771564,ID=W.mirabilis.21824;,.,+,W_mirabilis_21824,Chr01,1672072-1771564,gene,W_mirabilis_21824,+,dryad_ht76hdrdr

In [17]:
subset = pd.DataFrame(BED_nosplicing[["seqnames", "strand", "source", "type", "phase", "names", "gene_id", "start", "end"]])
subset.sort_values(by=["seqnames", "start"], inplace=True)
subset.to_csv(path+"Infer_Anth/data/gymnosperms/complete_genomes/welwitschia/welwitschia.nosplicing.tsv", sep="\t", index=None)

In [44]:
list_A = []
a=0
for i in range(5):
    for j in range(5):
        a+=1
        if j>i:    
            list_A.append(a)

print(list_A)

[2, 3, 4, 5, 8, 9, 10, 14, 15, 20]

## sequoia

In [8]:
#gfftobed -m G.montanum.final.gff > G.montanum.final.mRNA.bed
#bedtools merge -i G.montanum.final.mRNA.bed -delim "," -c 4,6 -o collapse > G.montanum.final.mRNA.merge.bed


prot_file =path+"Infer_Anth/data/gymnosperms/complete_genomes/sequoia/Segi.2_0.pep.fa"
bed_file = path+"Infer_Anth/data/gymnosperms/complete_genomes/sequoia/sequoia.mRNA.sorted.bed"

In [9]:
BED = pd.read_csv(bed_file, sep="\t", header=None, names=["chr", "start", "end", "id", "unk", "strand"])
BED.head()

        chr   start     end          id unk strand
0  HRSCAF_1  196859  206428  SEGI_32652   .      +
1  HRSCAF_1  233150  240139  SEGI_21818   .      -
2  HRSCAF_1  236038  236341  SEGI_00693   .      +
3  HRSCAF_1  237683  238535  SEGI_14446   .      -
4  HRSCAF_1  402892  429198  SEGI_34140   .      -

In [10]:
records = SeqIO.parse(prot_file, "fasta")
sequences = []
for rec in records:
    seq = SeqRecord(rec.seq, id=rec.name ,name="",description="")
    sequences.append(seq)


fasta_names = [seq.id for seq in sequences]

In [11]:
with open(path+"Infer_Anth/data/gymnosperms/complete_genomes/sequoia/sequoia.pep.fa", "w") as output_handle:
    SeqIO.write(sequences, output_handle, "fasta")

In [12]:
BED["names"]= BED.id
BED.head()

        chr   start     end          id unk strand       names
0  HRSCAF_1  196859  206428  SEGI_32652   .      +  SEGI_32652
1  HRSCAF_1  233150  240139  SEGI_21818   .      -  SEGI_21818
2  HRSCAF_1  236038  236341  SEGI_00693   .      +  SEGI_00693
3  HRSCAF_1  237683  238535  SEGI_14446   .      -  SEGI_14446
4  HRSCAF_1  402892  429198  SEGI_34140   .      -  SEGI_34140

In [13]:
BED_nosplicing = pd.DataFrame(BED[BED.names.isin(fasta_names)])
BED_nosplicing["seqnames"] = BED_nosplicing.chr
BED_nosplicing["ranges"] = [str(i)+"-"+str(j) for i,j in zip(BED_nosplicing["start"], BED_nosplicing["end"])]
BED_nosplicing["type"] = ["gene"]*len(BED_nosplicing)
BED_nosplicing["gene_id"] = BED_nosplicing["names"]
BED_nosplicing["phase"] = BED_nosplicing["strand"]
BED_nosplicing["source"] = ["treegenesdb"]*len(BED_nosplicing)
BED_nosplicing.head()

,chr,start,end,id,unk,strand,names,seqnames,ranges,type,gene_id,phase,source
0,HRSCAF_1,196859,206428,SEGI_32652,.,+,SEGI_32652,HRSCAF_1,196859-206428,gene,SEGI_32652,+,treegenesdb
1,HRSCAF_1,233150,240139,SEGI_21818,.,-,SEGI_21818,HRSCAF_1,233150-240139,gene,SEGI_21818,-,treegenesdb
2,HRSCAF_1,236038,236341,SEGI_00693,.,+,SEGI_00693,HRSCAF_1,236038-236341,gene,SEGI_00693,+,treegenesdb
3,HRSCAF_1,237683,238535,SEGI_14446,.,-,SEGI_14446,HRSCAF_1,237683-238535,gene,SEGI_14446,-,treegenesdb
4,HRSCAF_1,402892,429198,SEGI_34140,.,-,SEGI_34140,HRSCAF_1,402892-429198,gene,SEGI_34140,-,treegenesdb

In [14]:
subset = pd.DataFrame(BED_nosplicing[["seqnames", "strand", "source", "type", "phase", "names", "gene_id", "start", "end"]])
subset.sort_values(by=["seqnames", "start"], inplace=True)
subset.to_csv(path+"Infer_Anth/data/gymnosperms/complete_genomes/sequoia/sequoia.nosplicing.tsv", sep="\t", index=None)

### Thuja

In [15]:
prot_file =path+"Infer_Anth/data/gymnosperms/complete_genomes/thuja/Tplicata_572_v3.1.protein.fa"
bed_file = path+"Infer_Anth/data/gymnosperms/complete_genomes/thuja/Tplicata.mRNA.sorted.bed"

In [16]:
BED = pd.read_csv(bed_file, sep="\t", header=None, names=["chr", "start", "end", "id", "unk", "strand"])
BED.head()

,chr,start,end,id,unk,strand
0,10150191,16,527,ID=Thupl.10150191s0001.1.v3.1;Name=Thupl.10150...,.,+
1,10213767,73,382,ID=Thupl.10213767s0001.1.v3.1;Name=Thupl.10213...,.,-
2,10244434,0,1043,ID=Thupl.10244434s0001.1.v3.1;Name=Thupl.10244...,.,+
3,1033127,2291,2621,ID=Thupl.1033127s0001.1.v3.1;Name=Thupl.103312...,.,+
4,10732515,62,481,ID=Thupl.10732515s0001.1.v3.1;Name=Thupl.10732...,.,-

In [18]:
BED.chr[0:10]

0    10150191
1    10213767
2    10244434
3     1033127
4    10732515
5    10812532
6     1088380
7     1098077
8     1098077
9    11469472
Name: chr, dtype: object

### Pinus

In [45]:
prot_file =path+"Infer_Anth/data/gymnosperms/complete_genomes/pine/P.tabuliformis_V1.0.Protein.fa"
bed_file = path+"Infer_Anth/data/gymnosperms/complete_genomes/pine/P.tabuliformis_V1.0.mRNA.bed"
merge_bed_file = path+"Infer_Anth/data/gymnosperms/complete_genomes/pine/P.tabuliformis_V1.0.mRNA.subset.sort.merge.bed"

In [46]:
merge_BED = pd.read_csv(merge_bed_file, sep="\t", header=None, names=["chr", "start", "end", "id", "strand"], on_bad_lines="skip" )
merge_BED.head()

    chr   start     end                               id strand
0  chr1  205364  206554  ID=Pt1G00010.1;Parent=Pt1G00010      -
1  chr1  264323  312899  ID=Pt1G00020.1;Parent=Pt1G00020      -
2  chr1  333426  339639  ID=Pt1G00030.1;Parent=Pt1G00030      -
3  chr1  346197  346617  ID=Pt1G00040.1;Parent=Pt1G00040      +
4  chr1  382044  383576  ID=Pt1G00050.1;Parent=Pt1G00050      -

In [56]:
BED = pd.read_csv(bed_file, sep="\t", header=None, names=["chr", "start", "end", "id","unk1" , "strand"], on_bad_lines="skip" )
BED.head()

    chr   start     end                               id unk1 strand
0  chr1  205364  206554  ID=Pt1G00010.1;Parent=Pt1G00010    .      -
1  chr1  264323  312899  ID=Pt1G00020.1;Parent=Pt1G00020    .      -
2  chr1  333426  339639  ID=Pt1G00030.1;Parent=Pt1G00030    .      -
3  chr1  346197  346617  ID=Pt1G00040.1;Parent=Pt1G00040  420      +
4  chr1  382044  383576  ID=Pt1G00050.1;Parent=Pt1G00050    .      -

In [49]:
unique_seq = pd.DataFrame(merge_BED[[len(i.split(",")) == 1 for i in merge_BED.id.values]])
spliced_seq = pd.DataFrame(merge_BED[[len(i.split(",")) > 1 for i in merge_BED.id.values]])

In [50]:
unique_seq.head()

    chr   start     end                               id strand
0  chr1  205364  206554  ID=Pt1G00010.1;Parent=Pt1G00010      -
1  chr1  264323  312899  ID=Pt1G00020.1;Parent=Pt1G00020      -
2  chr1  333426  339639  ID=Pt1G00030.1;Parent=Pt1G00030      -
3  chr1  346197  346617  ID=Pt1G00040.1;Parent=Pt1G00040      +
4  chr1  382044  383576  ID=Pt1G00050.1;Parent=Pt1G00050      -

In [51]:
unique_seq["names"]= [i.split(";")[0].split("=")[1] for i in unique_seq.id]
unique_seq.head()

    chr   start     end                               id strand        names
0  chr1  205364  206554  ID=Pt1G00010.1;Parent=Pt1G00010      -  Pt1G00010.1
1  chr1  264323  312899  ID=Pt1G00020.1;Parent=Pt1G00020      -  Pt1G00020.1
2  chr1  333426  339639  ID=Pt1G00030.1;Parent=Pt1G00030      -  Pt1G00030.1
3  chr1  346197  346617  ID=Pt1G00040.1;Parent=Pt1G00040      +  Pt1G00040.1
4  chr1  382044  383576  ID=Pt1G00050.1;Parent=Pt1G00050      -  Pt1G00050.1

In [ ]:
#BED.to_csv(path+"Infer_Anth/data/gymnosperms/complete_genomes/pine/P.tabuliformis_V1.0.mRNA.subset.bed", sep="\t", header=None, index=None) ##no bad lines

In [15]:
records = SeqIO.parse(prot_file, "fasta")
sequences = []
for rec in records:
    seq = SeqRecord(rec.seq, id=rec.name ,name="",description="")
    sequences.append(seq)


fasta_names = [seq.id for seq in sequences]
sequences_dict = {i.id:i.seq for i in sequences}

In [23]:
spliced_seq.head()

,chr,start,end,id,strand
6,chr1,424311,426427,"ID=Pt1G00070.1;Parent=Pt1G00070,ID=Pt1G00070.4...","-,-,-,-,-,-,-"
11,chr1,1403858,1431838,"ID=Pt1G00120.2;Parent=Pt1G00120,ID=Pt1G00120.5...","-,-,-,-,-,+"
14,chr1,2782394,2866229,"ID=Pt1G00160.1;Parent=Pt1G00160,ID=Pt1G00160.2...","+,+,+,+,+,+,+"
17,chr1,4615714,4616794,"ID=Pt1G00190.1;Parent=Pt1G00190,ID=Pt1G00200.1...","-,+"
24,chr1,7814893,7815873,"ID=Pt1G00270.1;Parent=Pt1G00270,ID=Pt1G00270.2...","+,+"

In [30]:
##take name with longest sequence
uniq_name = []
not_in_fasta = []
for seq in spliced_seq["id"]:
    try :   
        A_list = [len(sequences_dict[name.split(";")[0].split("=")[1]]) for name in seq.split(",")]
        A_index = A_list.index(max(A_list)) 
        uniq_name.append(seq.split(",")[A_index])
    except KeyError:
        not_in_fasta.append(seq)

In [43]:
uniq_name[:10]

['ID=Pt1G00070.1;Parent=Pt1G00070',
 'ID=Pt1G00120.1;Parent=Pt1G00120',
 'ID=Pt1G00160.1;Parent=Pt1G00160',
 'ID=Pt1G00200.1;Parent=Pt1G00200',
 'ID=Pt1G00270.1;Parent=Pt1G00270',
 'ID=Pt1G00280.9;Parent=Pt1G00280',
 'ID=Pt1G00360.1;Parent=Pt1G00360',
 'ID=Pt1G00430.1;Parent=Pt1G00430',
 'ID=Pt1G00460.4;Parent=Pt1G00460',
 'ID=Pt1G00520.8;Parent=Pt1G00520']

In [40]:
uniq_name_bis = []
for splice in not_in_fasta: 
    in_fasta = [seq.split(";")[0].split("=")[1] for seq in splice.split(",") if seq.split(";")[0].split("=")[1] in sequences_dict]
    if len(in_fasta) > 0:
        A_list = [len(sequences_dict[name]) for name in in_fasta]
        A_index = A_list.index(max(A_list)) 
        uniq_name_bis.append(splice.split(",")[A_index])

In [42]:
uniq_name_bis

['ID=Pt1G07120.1;Parent=Pt1G07120',
 'ID=Pt2G58380.1;Parent=Pt2G58380',
 'ID=Pt4G18240.1;Parent=Pt4G18240',
 'ID=Pt7G19650.11;Parent=Pt7G19650',
 'ID=Pt8G12810.1;Parent=Pt8G12810',
 'ID=Pt0G03340.1;Parent=Pt0G03340']

In [53]:
all_spliced = uniq_name+uniq_name_bis

In [54]:
len(all_spliced)

20129

In [62]:
BED_unique = pd.DataFrame(BED[BED.id.isin(all_spliced)])

In [68]:
BED_unique["names"]= [i.split(";")[0].split("=")[1] for i in BED_unique.id]
BED_unique.drop(columns=['unk1'], inplace = True)
BED_unique.head()

,chr,start,end,id,strand,names
6,chr1,424311,426427,ID=Pt1G00070.1;Parent=Pt1G00070,-,Pt1G00070.1
17,chr1,1403858,1431838,ID=Pt1G00120.1;Parent=Pt1G00120,-,Pt1G00120.1
25,chr1,2782394,2866229,ID=Pt1G00160.1;Parent=Pt1G00160,+,Pt1G00160.1
35,chr1,4615957,4616794,ID=Pt1G00200.1;Parent=Pt1G00200,+,Pt1G00200.1
42,chr1,7814893,7815873,ID=Pt1G00270.1;Parent=Pt1G00270,+,Pt1G00270.1

In [85]:
BED_nosplicing = pd.concat([unique_seq, BED_unique], ignore_index=True)

In [86]:
BED_nosplicing.head()

    chr   start     end                               id strand        names
0  chr1  205364  206554  ID=Pt1G00010.1;Parent=Pt1G00010      -  Pt1G00010.1
1  chr1  264323  312899  ID=Pt1G00020.1;Parent=Pt1G00020      -  Pt1G00020.1
2  chr1  333426  339639  ID=Pt1G00030.1;Parent=Pt1G00030      -  Pt1G00030.1
3  chr1  346197  346617  ID=Pt1G00040.1;Parent=Pt1G00040      +  Pt1G00040.1
4  chr1  382044  383576  ID=Pt1G00050.1;Parent=Pt1G00050      -  Pt1G00050.1

In [88]:
longest_sequences = dict()
for id in sequences_dict:
    if id in BED_nosplicing.names.values:
        longest_sequences[id] = sequences_dict[id]

In [91]:
sequences = []
for rec in longest_sequences:
    seq = SeqRecord(longest_sequences[rec], id=rec ,name="",description="")
    sequences.append(seq)

fasta_names = [seq.id for seq in sequences]

In [90]:
with open(path+"Infer_Anth/data/gymnosperms/complete_genomes/pine/pinus_nosplicing.pep.fa", "w") as output_handle:
    SeqIO.write(sequences, output_handle, "fasta")

In [92]:
BED_nosplicing_fasta = pd.DataFrame(BED_nosplicing[BED_nosplicing.names.isin(fasta_names)])

In [93]:
BED_nosplicing_fasta["seqnames"] = BED_nosplicing_fasta.chr
BED_nosplicing_fasta["ranges"] = [str(i)+"-"+str(j) for i,j in zip(BED_nosplicing_fasta["start"], BED_nosplicing_fasta["end"])]
BED_nosplicing_fasta["type"] = ["gene"]*len(BED_nosplicing_fasta)
BED_nosplicing_fasta["gene_id"] = BED_nosplicing_fasta["names"]
BED_nosplicing_fasta["phase"] = BED_nosplicing_fasta["strand"]
BED_nosplicing_fasta["source"] = ["figshare"]*len(BED_nosplicing_fasta)
BED_nosplicing_fasta.head()

,chr,start,end,id,strand,names,seqnames,ranges,type,gene_id,phase,source
0,chr1,205364,206554,ID=Pt1G00010.1;Parent=Pt1G00010,-,Pt1G00010.1,chr1,205364-206554,gene,Pt1G00010.1,-,figshare
1,chr1,264323,312899,ID=Pt1G00020.1;Parent=Pt1G00020,-,Pt1G00020.1,chr1,264323-312899,gene,Pt1G00020.1,-,figshare
2,chr1,333426,339639,ID=Pt1G00030.1;Parent=Pt1G00030,-,Pt1G00030.1,chr1,333426-339639,gene,Pt1G00030.1,-,figshare
3,chr1,346197,346617,ID=Pt1G00040.1;Parent=Pt1G00040,+,Pt1G00040.1,chr1,346197-346617,gene,Pt1G00040.1,+,figshare
4,chr1,382044,383576,ID=Pt1G00050.1;Parent=Pt1G00050,-,Pt1G00050.1,chr1,382044-383576,gene,Pt1G00050.1,-,figshare

In [95]:
subset = pd.DataFrame(BED_nosplicing_fasta[["seqnames", "strand", "source", "type", "phase", "names", "gene_id", "start", "end"]])
subset.sort_values(by=["seqnames", "start"], inplace=True)
subset.to_csv(path+"Infer_Anth/data/gymnosperms/complete_genomes/pine/pinus.nosplicing.tsv", sep="\t", index=None)

In [96]:
len(subset)

72305

In [97]:
len(fasta_names)

72305